CREATE TABLE Employee (
  id         INT UNSIGNED AUTO_INCREMENT NOT NULL,
  first_name VARCHAR(250),
  last_name  VARCHAR(250),
  email      VARCHAR(250) NOT NULL UNIQUE,
  username   VARCHAR(250) NOT NULL UNIQUE,
  password   VARCHAR(255) NOT NULL,
  regdate    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
